spring:
  application:
    name: DARAM-server-V2
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:${DB_TYPE:mariadb}://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_SCHEMA:daram}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:123456}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
    generate-ddl: true
  data:
    mongodb:
      database: DARAM
      uri: ${MONGO_URL}
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  cache:
    jcache:
      config: classpath:ehcache.xml
    type: jcache
  elasticsearch:
    username: ${ES_USERNAME:elastic}
    password: ${ES_PASSWORD:changeme}
    uris: ${ES_URI:http://localhost:9200}
logging:
  level:
    root: info
    org.springframework.web: info
  file:
    path: ./logs/application.log
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    jmx:
      exposure:
        include: prometheus
token:
  secret: ${TOKEN_SECRET}
production:
  url: ${PROD_URL}
server:
  servlet:
    context-path: /api/v2