spring:
  application:
    name: DARAM-server-V2
  jackson:
    time-zone: Asia/Seoul
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:${DB_TYPE:mariadb}://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_SCHEMA:daram}?serverTimezone=KST
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:123456}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        jdbc:
          batch_size: 50
        dialect: org.hibernate.dialect.MariaDBDialect
        order_updates: true
        default_batch_fetch_size: 100
        use_sql_comments: true
        hibernate.type:
          print: true
    generate-ddl: true
  data:
    mongodb:
      database: DARAM
      uri: ${MONGO_URL}
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  cache:
    type: caffeine
logging:
  level:
    root: info
    org.springframework.web: info
  file:
    path: ./logs/application.log
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    jmx:
      exposure:
        include: prometheus
token:
  secret: ${TOKEN_SECRET}
production:
  url: ${PROD_URL}
server:
  servlet:
    context-path: /api/v2