spring:
  application:
    name: DARAM-server-Dev
  jackson:
    time-zone: Asia/Seoul
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:${DB_TYPE:mariadb}://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_SCHEMA:daram}?serverTimezone=Asia/Seoul
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:123456}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        jdbc:
          batch_size: 50
        dialect: org.hibernate.dialect.MySQLDialect
        order_updates: true
        default_batch_fetch_size: 100
        use_sql_comments: true
        hibernate.type:
          print: true
    generate-ddl: true
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  cache:
    type: caffeine
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: "http://localhost:5173/login/oauth2/code/google"
            scope:
              - email
              - profile
            authorization-grant-type: authorization_code
            client-name: google
logging:
  level:
    root: info
    org.springframework.security: debug
    org.springframework.web: info
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    jmx:
      exposure:
        include: prometheus
token:
  secret: ${TOKEN_SECRET}
jwt:
  secret: ${JWT_SECRET}
  access-token-validity: 3600
  refresh-token-validity: 604800
production:
  url: ${PROD_URL}
  front-url: ${FRONT_URL}
server:
  servlet:
    context-path: /dev-server/daram
  port: ${PORT:52308}