name: Docker Build Test by Push
on:
  push: { branches: [ "main" ] }
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker
        run: |
          sudo apt-get update
          sudo apt-get remove --purge containerd containerd.io
          sudo apt-get install -y docker.io
          sudo systemctl enable --now docker
          sudo usermod -aG docker $USER
          docker --version
      - name: Build Docker Image
        run: docker build -t test-image .
      - name: Run Docker Image
        run: |
          docker run -d -p 8080:8080 test-image
          docker ps
      - name: Stop Docker Container
        run: docker ps -q | xargs docker stop