name: DeployServer
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Connect deploy key
        uses: cloudtype-github-actions/connect@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          ghtoken: ${{ secrets.GHP_TOKEN }}
      - name: Deploy
        uses: cloudtype-github-actions/deploy@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          project: snowykte0426/daram
          stage: main
          yaml: >
            name: daram-server-v2
            app: dockerfile
            options:
              ports: "8080"
              dockerfile: Dockerfile
              env:
                - name: AWS_ACCESS_KEY
                  value: ${{ secrets.AWS_ACCESS_KEY }}
                - name: AWS_REGION
                  value: ${{ secrets.AWS_REGION }}
                - name: AWS_S3_BUCKET_NAME
                  value: ${{ secrets.AWS_S3_BUCKET_NAME }}
                - name: AWS_S3_ENDPOINT
                  value: ${{ secrets.AWS_S3_ENDPOINT }}
                - name: AWS_SECRET_KEY
                  value: ${{ secrets.AWS_SECRET_KEY }}
                - name: CLOUDFLARE_BUCKET_SUBDOMAIN
                  value: ${{ secrets.CLOUDFLARE_BUCKET_SUBDOMAIN }}
                - name: FRONT_URL
                  value: ${{ secrets.FRONT_URL }}
                - name: GOOGLE_CLIENT_ID
                  value: ${{ secrets.GOOGLE_CLIENT_ID }}
                - name: GOOGLE_CLIENT_SECRET
                  value: ${{ secrets.GOOGLE_CLIENT_SECRET }}
                - name: GOOGLE_REDIRECT_URL
                  value: ${{ secrets.GOOGLE_REDIRECT_URL }}
                - name: JWT_SECRET
                  value: ${{ secrets.JWT_SECRET }}
                - name: MONGO_URL
                  value: ${{ secrets.MONGO_URL }}
                - name: PROD_URL
                  value: ${{ secrets.PROD_URL }}
                - name: REDIS_HOST
                  value: ${{ secrets.REDIS_HOST }}
                - name: REDIS_PORT
                  value: ${{ secrets.REDIS_PORT }}
                - name: TOKEN_SECRET
                  value: ${{ secrets.TOKEN_SECRET }}
                - name: DB_HOST
                  value: ${{ secrets.DB_HOST }}
                - name: DB_PORT
                  value: ${{ secrets.DB_PORT }}
              args: []
            context:
              git:
                url: git@github.com:${{ github.repository }}.git
                ref: ${{ github.ref }}
              preset: dockerfile