name: Deploy to cloudtype
on:
  workflow_run:
    workflows: [ "Gradle Build Test" ]
    types:
      - completed
jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Connect deploy key
        uses: cloudtype-github-actions/connect@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          ghtoken: ${{ secrets.GHP_TOKEN }}
      - name: Deploy
        uses: cloudtype-github-actions/deploy@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          project: snowykte0426/daram
          stage: main
          yaml: >
            name: daram-server-v2

            app: java@21

            options:
              ports: "8080"
              env:
                AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
                AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
                AWS_REGION: ${{ secrets.AWS_REGION }}
                AWS_S3_BUCKET_NAME: ${{ secrets.AWS_S3_BUCKET_NAME }}
                AWS_S3_ENDPOINT: ${{ secrets.AWS_S3_ENDPOINT }}
                DB_HOST: ${{ secrets.DB_HOST }}
                DB_PORT: ${{ secrets.DB_PORT }}
                DB_USERNAME: ${{ secrets.DB_USERNAME }}
                DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
                DB_SCHEMA: ${{ secrets.DB_SCHEMA }}
                DB_TYPE: ${{ secrets.DB_TYPE }}
                REDIS_HOST: ${{ secrets.REDIS_HOST }}
                REDIS_PORT: ${{ secrets.REDIS_PORT }}
                JWT_SECRET: ${{ secrets.JWT_SECRET }}
              buildenv: []
              build: ./gradlew build
            context:
              git:
                url: git@github.com:${{ github.repository }}.git
                ref: ${{ github.ref }}
              preset: java-springboot