name: Deploy to cloudtype
on:
  push:
    branches:
      - main
jobs:
  # deploy:  # 주석 처리된 작업
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2
  #     - name: Connect deploy key
  #       uses: cloudtype-github-actions/connect@v1
  #       with:
  #         token: ${{ secrets.CLOUDTYPE_TOKEN }}
  #         ghtoken: ${{ secrets.GHP_TOKEN }}
  #     - name: Deploy
  #       uses: cloudtype-github-actions/deploy@v1
  #       with:
  #         token: ${{ secrets.CLOUDTYPE_TOKEN }}
  #         project: snowykte0426/daram
  #         stage: main
  #         yaml: >
  #           name: daram-server-v2
  #           app: java@21
  #           options:
  #             ports: "8080"
  #             env:
  #               - name: DB_HOST
  #                 value: ${{ secrets.DB_HOST }}
  #               - name: DB_PORT
  #                 value: ${{ secrets.DB_PORT }}
  #               - name: DB_USERNAME
  #                 value: ${{ secrets.DB_USERNAME }}
  #               - name: DB_PASSWORD
  #                 value: ${{ secrets.DB_PASSWORD }}
  #               - name: DB_SCHEMA
  #                 value: ${{ secrets.DB_SCHEMA }}
  #               - name: DB_TYPE
  #                 value: ${{ secrets.DB_TYPE }}
  #               - name: REDIS_HOST
  #                 value: ${{ secrets.REDIS_HOST }}
  #               - name: REDIS_PORT
  #                 value: ${{ secrets.REDIS_PORT }}
  #               - name: JWT_SECRET
  #                 value: ${{ secrets.JWT_SECRET }}
  #             buildenv: []
  #             build: ./gradlew build
  #           context:
  #             git:
  #               url: git@github.com:${{ github.repository }}.git
  #             ref: ${{ github.ref }}
  #             preset: java-springboot
