name: ReviewCodeRabbit
on:
  pull_request:
    types: [opened, synchronize]
jobs:
  code_review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run CodeRabbit
        uses: coderabbitai/coderabbit-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          coderabbit_api_key: ${{ secrets.CODERABBIT_API_KEY }}